### ISSUE TITLE
Conflict with Quilt

### ISSUE THREAD

**Issue by SuperKnux** [Emafire003/LightWithin#10]
**Describe the bug**
The mod is conflicting with Quilt with it and the status effect api redirecting the same spot.

**To Reproduce**
1. Install Quilt
2. Add Light Within and its' dependencies
3. Attempt to launch the game
4.                                                                                                                                                       pain

**Version information**
LightWithin mod version: <0.3.1>
Minecraft Version: <1.19.2>
Fabric API version: <version>
(Usually not required, but could be helpful if you want)
Dependencies version: <coloredglowlib version> <cardinal components version> ecc

**Expected behavior**
Add this only if it's not something like "The game crashes. It shouldn't do it".

**Screenshots and files**
These are optional, but could be helpful especially files like the server/client log (located in /logs/ if on the server and %appdata%/.minecraft/logs on client) and the crash reports. 
**Additional context**

**Comment by Emafire003** [comment]
Could you send me the logs to have a more precise idea of what's happening?
Anyway, I'll try to fix it in the next release but I have no idea when that will be sine I'm finisihing up the alpha release of anther cool (and a bit complicated) project and I should also be studying for this semester's exams. I'll try my best tho

**Comment by Emafire003** [comment]
Quilt won't be supported for now. I may add compatibility at a later time.
