### ISSUE TITLE
[Info Request] Will development continue?

### ISSUE THREAD

**Issue by Slayer5934** [Emafire003/LightWithin#11]
Hello, I love this mod as it is very unique and fun;
I am looking to add it to my upcoming modpack in the Tekxit series, is development going to continue? I look forward to any update even if it is further down the line (:

**Comment by Emafire003** [comment]
It most likely will continue, not sure when tho since I am focusing on something else at the moment.

**Comment by Emafire003** [comment]
I will push the updated version shortly. It's going to be release for 1.20.1 and 1.20.4
