### ISSUE TITLE
1.19.2 Config request: Everlasting Light

### ISSUE THREAD

**Issue by Ryuco** [Emafire003/LightWithin#13]
For mods like origin which can cause players to lose the ability to eat this mod is highly incompatible due to not being able to use the foods, would it be possible to add a config which allows players to activate their light without meeting requirements/eating the foods for 1.19.2?

**Comment by Emafire003** [comment]
First of all I am currently going to mantain only the 1.20.1 and 1.20.4 versions, sorry but I have kind of changed almost all of the code.
Then, eating food is not really the primary way to activate a light, the trigger requirements are, and imo in the latest versions they became a lot better. If you want, there also is the trigger_config file where you can set the min trigger threshold to zero to activate basicly every time you get hit/hit something or whatever is the actual trigger.

But, I will consider adding an option to actiavate the light whenerver you want, but it goes kind of against the idea behind this mod. And also it would be kind of a problem in regards of balancing everything. Like the cooldown should be wayyyyy longer or something

**Comment by Ryuco** [comment]
Perfectly understandable to work only on your later stuff, and yeah the everlasting light idea would require balancing. although i do think its a good idea to leave the option so that servers could fine tune it for their specific ideas whether that be by having built in stuff or just leaving it so that the servers have the responsibility for the balancing.

**Comment by Emafire003** [comment]
I think [this](https://github.com/Emafire003/LightWithin/blob/35c605021e93f4722d193b92f68cae5b61a2c85a/changelog.md) is a good enough compromise.

**Comment by Emafire003** [comment]
Also, let me know your opinion about this implementation.
