### ISSUE TITLE
Please Fix Quilt Mod Loading Issue

### ISSUE THREAD

**Issue by AcoYTMC** [Emafire003/LightWithin#19]
### Discussed in https://github.com/Emafire003/LightWithin/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **AcoYTMC** June 30, 2024</sup>
The Mod Can't Be Run On Quilt Because Of Your MilkNotCleanLightEffectsMixin Mixin Class, I Tried Asking Someone On The Official Fabric Development Discord For How To Improve It And Someone Said
:
:
"...that doesn't seem like a very good way to accomplish that at all
It totally ruins mod compat, because then only light within effects will not be cleared
And if that mod is loaded, there's nothing you can do about it
So to answer your question, yes there is a better way
I would inject into clearStatusEffects WrapWithCondition the iterator.remove call if the status effect is your status effect and a boolean is true
Then I would inject at the head and tail of milk bucket's finishUsing method and set the boolean to true, then false respectively"
:
:
They also gave an example
:
:
// some boolean in one of your non-mixin classes
boolean bool = false;
// mixin class for MilkBucketItem
@Inject(method = "finishUsing", at = @At("HEAD"))
private void setBoolTrue(){
  bool = true;
}

@Inject(method = "finishUsing", at = @At("RETURN"))
private void resetBool(){
  bool = false;
}

// mixin class for LivingEntity
    @WrapWithCondition(method = "clearStatusEffects", at = @At(value = "INVOKE", target = "Ljava/util/Iterator;remove()V"))
private boolean noRemove(/*whatever the args are*/) {
  if (bool && /* check if the status effect is a non-removable status effect */) {
    return false;
  }
  return true;
}
:
:
If You Could Do This It Would Make My Life So Much Easier But I Know You're Busy So I'm Able To Wait</div>

**Comment by Emafire003** [comment]
Please Don't Write Stuff Like This It Really Hurts My Eyes.

Also for context, that code bit is fairly old and yes, I was thinking about improving it sometime. But I'm not sure it's the only thing impacting on the quilt compat thing. However, I'll see what I can do, but quilt support is not a priority at the moment, sorry! Thank you anyway

**Comment by AcoYTMC** [comment]
Sorry about that, i'm just trying to make a server and innerlights (among other things) is the main focus but it's on quilt

**Comment by Emafire003** [comment]
Apparently, it was indeed just the bucket causing issues with quilt. Will do a bit more testing the release 1.1.2 for minecraft 1.20.1, 1.19.2 and 1.21
