### ISSUE TITLE
I tried to make my light work, and when i managed to do that by healing my pet dog game crashed

### ISSUE THREAD

**Issue by Givoric** [Emafire003/LightWithin#2]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 23/07/22, 10:54
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1293.method_5584()" because the return value of "net.minecraft.class_1309.method_6112(net.minecraft.class_1291)" is null
	at me.emafire003.dev.lightwithin.lights.HealLight.execute(HealLight.java:86)
	at me.emafire003.dev.lightwithin.LightWithin.activateHeal(LightWithin.java:223)
	at me.emafire003.dev.lightwithin.LightWithin.activateLight(LightWithin.java:152)
	at me.emafire003.dev.lightwithin.items.LuxintusBerryItem.method_7861(LuxintusBerryItem.java:56)
	at net.minecraft.class_1799.handler$bmj000$finishUsingItem(class_1799.java:1148)
	at net.minecraft.class_1799.method_7910(class_1799.java)
	at net.minecraft.class_1309.method_6040(class_1309.java:3103)
	at net.minecraft.class_3222.method_6040(class_3222.java:1176)
	at net.minecraft.class_1309.method_37119(class_1309.java:2982)
	at net.minecraft.class_3222.method_37119(class_3222.java:1674)
	at net.minecraft.class_1309.method_6076(class_1309.java:2969)
	at net.minecraft.class_1309.method_5773(class_1309.java:2347)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:485)
	at net.minecraft.class_3244.method_18784(class_3244.java:241)
	at net.minecraft.class_2535.method_10754(class_2535.java:246)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.emafire003.dev.lightwithin.lights.HealLight.execute(HealLight.java:86)
	at me.emafire003.dev.lightwithin.LightWithin.activateHeal(LightWithin.java:223)
	at me.emafire003.dev.lightwithin.LightWithin.activateLight(LightWithin.java:152)
	at me.emafire003.dev.lightwithin.items.LuxintusBerryItem.method_7861(LuxintusBerryItem.java:56)
	at net.minecraft.class_1799.handler$bmj000$finishUsingItem(class_1799.java:1148)
	at net.minecraft.class_1799.method_7910(class_1799.java)
	at net.minecraft.class_1309.method_6040(class_1309.java:3103)
	at net.minecraft.class_3222.method_6040(class_3222.java:1176)
	at net.minecraft.class_1309.method_37119(class_1309.java:2982)
	at net.minecraft.class_3222.method_37119(class_3222.java:1674)
	at net.minecraft.class_1309.method_6076(class_1309.java:2969)
	at net.minecraft.class_1309.method_5773(class_1309.java:2347)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 15839
	Entity Name: Givoric
	Entity's Exact location: 1274.41, 61.99, 31.15
	Entity's Block location: World: (1274,61,31), Section: (at 10,13,15 in 79,3,1; chunk contains blocks 1264,-64,16 to 1279,319,31), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,-64,0 to 1535,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:485)
	at net.minecraft.class_3244.method_18784(class_3244.java:241)
	at net.minecraft.class_2535.method_10754(class_2535.java:246)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1709172560 bytes (1629 MiB) / 6274678784 bytes (5984 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2,59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8280
	Graphics card #1 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095,00
	Graphics card #1 deviceId: 0x249d
	Graphics card #1 versionInfo: DriverVersion=30.0.14.9676
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23261,38
	Virtual memory used (MB): 19917,41
	Swap memory total (MB): 7046,33
	Swap memory used (MB): 245,25
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alaskanativecraft: Alaska Native Craft 1.4.6
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.31
		armorchroma: Armor Chroma 1.2.2
		attributefix: AttributeFix 15.0.2
		backslot: BackSlot 1.2.8
			amecsapi: Amecs API 1.3.6+mc22w17a
		backslotaddon: BackSlot Addon 1.0.9
		balm-fabric: Balm 4.3.0+0
		bclib: BCLib 2.0.16
		bedspreads: Bedspreads 6.0.0-beta.1+1.19
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.0.9
		betternether: Better Nether 7.0.6
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.8.1
		bettervillage: Better Village 1.0.2
		bookshelf: Bookshelf 14.1.7
		borderlessmining: Borderless Mining 1.1.5+1.19
		cameraoverhaul: Camera Overhaul 1.3.0-fabric-universal
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.2.7
			crowdin-translate: CrowdinTranslate 1.4+1.19
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		chalk: Chalk 2.1.0+1.19
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 6.0.0-beta.2+1.19
		chime: Chime 1.3.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		clear-skies: Clear Skies 2.0.94
		cleardespawn: Clear Despawn 1.1.8
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.73
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		coloredglowlib: ColoredGlow Lib 1.3.4
		comforts: Comforts 6.0.0-beta.4+1.19
			spectrelib: SpectreLib 0.8.1+1.19
		continuity: Continuity 2.0.0+1.19
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.7.2
		creeperoverhaul: Creeper Overhaul 2.0.1
		crops_love_rain: Crops Love Rain 1.3.0
		cryingportals-fabric: Crying Portals (Fabric) 1.3
		cullleaves: Cull Leaves 2.3.4
		customizableelytra: Customizable Elytra 1.6.0-1.19
		cyclepaintings-fabric: Cycle Paintings (Fabric) 2.3
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dangerousstonecutter: Dangerous Stone Cutter 1.5
		dark-loading-screen: Dark Loading Screen 1.6.12
		darkness: True Darkness 2.0.94
		deathknell: DeathKnell 4.0.1
		deathlog: DeathLog 0.2.10+1.19
		dehydration: Dehydration 1.2.9
		display_case: Display Case Mod 1.0.2
		dual_riders: Dual Riders 1.1.2
		dynamicfps: Dynamic FPS 2.2.0
		eatinganimationid: Eating Animation 1.8.1
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 11.0.4
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.7
		entity_texture_features: Entity Texture Features 3.1.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fabrictailor: Fabric Tailor 1.8.4
			config2brigadier: Config to Brigadier 1.1.3
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabsit: FabSit 1.4.0+1.19
		fallingtree: FallingTree 3.7.4
		farsight: Farsight Mod 1.19-2.0
		ferritecore: FerriteCore 4.2.1
		flytre_lib: FlytreLib 1.8.8
		forgeconfigapiport: Forge Config API Port 4.0.0
		geckolib3: Geckolib 3.1.0
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		guiclock-fabric: GUI Clock (Fabric) 3.2
		guicompass-fabric: GUI Compass (Fabric) 2.3
		hangman: Left Hanging 4.2.0.3
		hardcorerevival: Hardcore Revival 9.0.0
		herdspanic: Herds Panic 1.0.6
		here-be-no-dragons: Here be no Dragons! 1.0.0
		horseinboat: HorseInBoat 1.1.3
		iceberg: Iceberg 1.0.38
		immersive_paintings: Immersive Paintings 0.1.5+1.19
		impaled: Impaled 1.1.4
		indium: Indium 1.0.6+mc1.19
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		jade: Jade 7.4.0
		java: OpenJDK 64-Bit Server VM 17
		jrhc: Jingames Hair C 1.4
		justplayerheads-fabric: Just Player Heads (Fabric) 2.1
		kleeslabs: KleeSlabs 12.0.0
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		libraryferret: Library Ferret 2.0.0
		lightwithin: LightWithin Mod 0.1.1
			renderer: Renderer 1.0
		lootr: Lootr 0.4.21.60
		lovely_snails: Lovely Snails 1.1.0+1.19
		mavm: More Axolotl Variants Mod 1.1.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		medievalweapons: Medieval Weapons 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		megaparrot: Megaparrot 1.0.5
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		more-axolotls: More Axolotls 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 4.0.2
		mythicmounts: Mythic Mounts 1.19-7.0
		netherportalfix: NetherPortalFix 10.0.0
		no-shield-delay: No Shield Delay 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.19-rc2
		observed: Observed 1.3.2
		onsoulfire: On Soul Fire 1.19-2
		patchouli: Patchouli 1.19-74-FABRIC
		physicsmod: Physics Mod 2.7.6
		playerabilitylib: Pal 1.6.0
		pling: Pling 1.5.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		puddles: Puddles 1.2.2
		puzzleslib: Puzzles Lib 4.0.17
		realisticfirespread: Realistic Fire Spread 1.19-2
		recipecache: recipecache 0.2.0-1.19
		roughlyenoughitems: Roughly Enough Items 9.1.517
		ruined_equipment: Ruined Equipment 2.0.0
		sandwichable: Sandwichable 1.3.a+1.19
		satin: Satin 1.9.0
		sheepconsistency: Sheep Consistency 1.0.4
		shouldersurfing: Shoulder Surfing Reloaded 2.2.7
		simplehats: SimpleHats 1.19-0.1.2
		skeletonfix: Skeleton Aiming Fix 1.1.2+1.19
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		skylorlib: SkyLib 1.5.1
		slimyboyos: Slimy Boyos 5.0.0.1
		slimyfloor: Slimy Floor 1.19-1.2.4
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		solid_mobs: Solid Mobs 1.3
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.9
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		strawdummy: Straw Dummy 1.8.0
		talkbubbles: Talk Bubbles 1.0.2
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.6+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.1+1.19
		villagernames: Villager Names 4.0.5
		visualoverhaul: VisualOverhaul 4.1.1
		visualworkbench: Visual Workbench 4.0.0
		waveycapes: WaveyCapes 1.2.0
		waystones: Waystones 11.0.1
		wwoo: William Wythers' Overhauled Overworld 2.2+1.19
			ikwid_fabric: I know what I'm doing! [FABRIC] 1.1+1.18.2
		xps: Xp Obelisk 0.4.1.r_for_1.19.x_Fabric
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Loaded Shaderpack: Tea_V1.5.7.zip
		Profile: Custom (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Givoric'/15839, l='ServerLevel[1.19 mods test 5]', x=1274.41, y=61.99, z=31.15]]
	Data Packs: vanilla, Fabric Mods, file/combatlogging.zip (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.8-1.19

**Comment by Emafire003** [comment]
Could you please install Not Enough Crashes and repeat what you did? I'll into it in a bit myself anyway

**Comment by Emafire003** [comment]
Ok found the problem, testing a fix now, will release a hotfix version soon. Thanks for the report!
