### ISSUE TITLE
The game crashes when using the frost ability

### ISSUE THREAD

**Issue by AcoYTMC** [Emafire003/LightWithin#20]
The game crashes when using the frost ability

**Version information**
LightWithin mod version: 1.1.1+1.19.2
Minecraft Version: 1.19.2
Fabric API version: 0.77.0+1.19.2

(Usually not required, but could be helpful if you want)
Dependencies version: <versions>

I Wanted It To Freeze The Player In Place

[crash-2024-07-05_14.24.45-server.txt](https://github.com/user-attachments/files/16113866/crash-2024-07-05_14.24.45-server.txt)

I was hosting a world with essential

**Comment by AcoYTMC** [comment]
it's using structure placer api 1.1.4 which is for minecraft 1.20 but it's 1.19.2

**Comment by Emafire003** [comment]
Yep I noticed, wrong build used, will fix tomorrow

**Comment by AcoYTMC** [comment]
Thank You
