### ISSUE TITLE
resource pack is badly setup

### ISSUE THREAD

**Issue by spaghettube** [Emafire003/LightWithin#22]
hey, cool mod! the audio resource pack you provide is a folder inside a zip (its not supposed to have a folder there):
![image](https://github.com/user-attachments/assets/f93f1147-26c1-47f6-8762-8f883dd0e932)

**Comment by Emafire003** [comment]
Ah sorry. For now just extract it, I will update the pack in a bit.

**Comment by Emafire003** [comment]
I updated it on modrinth, I don't think I will be updating the one in the github files. Anyways, it should be fixed now, let me know if you find any other problems!
