### ISSUE TITLE
config keeps clearing

### ISSUE THREAD

**Issue by spaghettube** [Emafire003/LightWithin#23]
**Describe the bug**
everytime i restart my mc, the lightwithin config just seemingly resets? i keep hiding the icons and stuff and they keep on coming back after rejoining

**To Reproduce**
1- change the config
2- relaunch game

**Version information**
LightWithin mod version: <1.1.2>
Minecraft Version: <1.20.1>
Fabric API version: <0.92.2>

**Expected behavior**
config shouldnt reset

**Screenshots and files**
none

**Comment by Emafire003** [comment]
Can you please send the logs as well?

**Comment by spaghettube** [comment]
before, after, or before and after?

**Comment by Emafire003** [comment]
Both, but mainly the full log after you have changed the settings

**Comment by Emafire003** [comment]
Hey, if you want to help https://github.com/Emafire003/LightWithin/releases/tag/v1.1.3-dev try out that version and let me know if the issue keeps happening. (It shouldn't)
