### ISSUE TITLE
Cannot connect to a server, confid desync

### ISSUE THREAD

**Issue by HeatUp0** [Emafire003/LightWithin#24]
Im trying to play on a modded server with some friends but nobody can join the server, anytime we join we get instantly kicked for "Failed to encode packet 'clientbound/minecraft:custom_payload' (lightwithin:light_config_sync)"
This bug completely disables anyone from joining the server/

**To Reproduce**
1. Start server with this mod
2. start your own game with this mod
3. attempt to join the server

**Version information**
LightWithin mod version: <LightWithin - 1.1.2+1.21>
Minecraft Version: <1.21>
Fabric API version: <0.16.0>

**Expected behavior**
I should just be able to join the server

**Screenshots and files**
These are optional, but could be helpful especially files like the server/client log (located in /logs/ if on the server and %appdata%/.minecraft/logs on client) and the crash reports. 

**Additional context**
I have tried both putting the config files exclusive to the server in my configs folder and putting my client config into the server and neither work.

**Comment by Emafire003** [comment]
Could you please send the full logs both of the client and the sever? (They should also include a list of all the mods loaded which could be useful). Last question, are you using Fabric or Quilt? Because `Fabric api version <0.16.0>`  seems strange, since the one for 1.21 starts with ` 0.100.x`

**Comment by Emafire003** [comment]
Can you please also try the same thing with https://github.com/Emafire003/LightWithin/releases/tag/v1.1.3%2B1.21-dev this build and send the logs with that? I've added some more logging to try and understand what's happening. Also are you using the same version of the mod both on the client and server? And are you using via version or something like that? (packets changed a lot between 1.20.4 and 1.20.5 so joining with different versions may cause issues)

**Comment by HeatUp0** [comment]
Im using fabric i just excluded the 0.100.x when copy and pasting the version lol. Im also using the exact same version of the mod on the server as i copy and pasted my mod list to the server to begin with. Ill get back to you with those logs when i can but for the time being ive started the server without the mod and the logs for it have been overwritten as they werent crashes so they werent stored

**Comment by Emafire003** [comment]
The logs should haveb remained as zip files named with the date time they were creared

**Comment by Emafire003** [comment]
Should be fixed now. I didn't update the networking code correctly it seems
