### ISSUE TITLE
Cant eat all three types of berries with a certain mod

### ISSUE THREAD

**Issue by AWeebCoding** [Emafire003/LightWithin#26]
Cant eat the berries cuz Carnivore

Downloaded the origins mod, chose Carnivore, and i cant eat the berries. is there a way that you can categorize it as not a fruit?

**Comment by Emafire003** [comment]
Uhm sorry but that's a debuff you chose for yourself by selecting that origin. You can still trigger your light either naturally or using charges.
You can't currently change it or use the luxcognita but I may think of something in the future. 

(As you said in your original messages, yes berries are fruit)

**Comment by Nidoskull** [comment]
It's possible to add these berries to the origins:ignore_diet tag to let you eat them whether you're a carnivore, vegetarian, or something else.
