### ISSUE TITLE
Configuration for light settings

### ISSUE THREAD

**Issue by IdrisQe** [Emafire003/LightWithin#4]
So first off, I just want to say this is an incredible mod idea! You don't see the concept of (psuedo)random player-unique stats in many mods despite it being a really cool way to shake things up, and the mechanics themselves seem both simple enough to not be obtuse but also complex enough to feel different.

That said, the UUID-based nature of it could also be a sticking point for many who end up with an unfavourable light. So to remedy this, at least for those who like to tweak their mod configs to their liking, I have a few suggestions:

-Seed-based light: A config option to mix the world seed with the player UUID to generate the light and associated stats, so one player could potentially try all kinds of lights, but still have which one they have feel random and unique per playthrough. Not suggesting this be the default of course, but it would be a cool option!

-Commands for admins to manually set people's light stats in the server: For those who really don't want to engage with the randomness, a way to set lights manually so nobody has too much of an advantage over others from luck-of-the-draw.

**Comment by Emafire003** [comment]
Thank you for the appreciation, but you see, I've already implemented a way to change the light type, I *might* add a way to change the other stats as well. For the commands check the 1.1.0 update
