### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by PersonGuy46** [Emafire003/LightWithin#5]
Whenever I try to create a world with this mod along with cardinal components api, it kicks me before I enter the world back into the server menu with the prompt "Invalid player data."

**Comment by Emafire003** [comment]
I think I sorta know what's going on, but could you send the logs real quick? And, if you have updated the mod did u remove the old config?

**Comment by Emafire003** [comment]
Also could you send me you UUID or minecraft username? Maybe it's trying to generate something that isn't really possibile yet and so the player data gets invalidated.

**Comment by Emafire003** [comment]
Let me know if the new release work, so I can close the issue (and more importantly be sure that I've fixed the right thing)

**Comment by Emafire003** [comment]
I'm sorry, can you confirm me the issue has been resolved? (I'll consider the issue solved if I'll get no answer by tomorrow)
