### ISSUE TITLE
[Suggestion]  Have lights optionally "self activate"

### ISSUE THREAD

**Issue by MLMII** [Emafire003/LightWithin#7]
Yeah, I read the lore spoiler and it got me thinking that as an config option perhaps lights could self activate instead of requiring a button press.  

Granted, as a defensive light wielder, my perspective might be colored ever so slightly by the convience of not having to worry about hitting the activation button in the midst of a mob swarm at a couple of hearts.   *wink*

Thank you for your time

**Comment by Emafire003** [comment]
Well, originally it would have been automatic but with some lights it would have been a problem. But yes I think I could still create a config option for it!
