### ISSUE TITLE
Crash on loading into world due to Exception in Server Tick Loop

### ISSUE THREAD

**Issue by Tr33stan** [Emafire003/LightWithin#9]
On loading into a world the client crashes, attached below is a paste of the error message in the crash log.

java.lang.IncompatibleClassChangeError: Expected static method 'voidme.emafire003.dev.coloredglowlib.ColoredGlowLib.setOverrideTeamColors(boolean)'
	at me.emafire003.dev.lightwithin.LightWithin.lambda$onInitialize$0(LightWithin.java:97)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bhf000$afterSetupServer(MinecraftServer.java:4801)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Version information**
LightWithin mod version: <0.3.0>
Minecraft Version: <1.19.2>
Fabric API version: <0.62.0>
Dependencies version: <coloredglowlib version 2.0.1> <cardinal components version 5.0.2> ecc

I more assemble modpacks than do any real coding, but whilst it appears to me to be an issue between lightwithin & coloredglowlib, here is a full list of the currently used mods as well, just in case there is some other interaction occuring.
advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		alloy_forgery: Alloy Forgery 2.0.16+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.2.46
		aureate: Aureate Reliquary 1.19.x-release.7
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		awesomedungeon: Awesome dungeon 3.0.0
		awesomedungeonocean: Awesome dungeon edition ocean 3.0.1
		axesareweapons: Axes Are Weapons 1.6.0
		basicshields: Basic Shields [Fabric] 1.4.0-pre2-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		bettercombat: Better Combat 1.4.4+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.0
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.8.1
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bloodshed: Bloodshed (Fabric) 1.0.3
		bookshelf: Bookshelf 16.1.5
		bucolicorigins: Bucolic_Origins[FABRIC] 3.5
		bydesign: By Design 1.0.3
		byg: Oh The Biomes You'll Go 2.0.0.12
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		chestcavity: Chest Cavity 2.16.3
			modify-drops-api: Modify Drops API 0.4.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		coloredglowlib: ColoredGlow Lib 2.0.1+fabric_1.19.2
		combatroll: Combat Roll 1.0.8+1.19
		continents: Continents 1.1
		ctov: ChoiceTheorem's Overhauled Villages 3.1
		cull-less-leaves: Cull Less Leaves 1.0.6
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			conditional-mixin: conditional mixin 0.3.0
		dataattributes: Data Attributes 1.2.7
		dawn: Dawn API 3.5.0
		deeperdarker: Deeper And Darker 1.0.2b-fabric
			customportalapi: Custom Portal Api 0.0.1-beta52-1.19
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		ecologics: Ecologics 2.1.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
			mm: Manningham Mills 2.3
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.2.0
		forgeconfigapiport: Forge Config API Port 4.2.6
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.22
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		graveyard_biomes: The Graveyard Biomes 1.2
		guarding: Guarding 1.19+2.1.0
		hookshot: Hookshot 26.0
		hudium: Hudium 1.4.5+mc1.19
			omega-config: OmegaConfig 1.3-1.19-pre5
			spruceui: SpruceUI 4.0.0+1.19
		iceberg: Iceberg 1.0.46
		idwtialsimmoedm: idwtialsimmoedm 0.1.3+1.19
		impaled: Impaled 1.1.4
		incapacitated: Incapacitated 1.3-1.19.2
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		keyblademod: Keyblade Mod 1.0.2
		labels: labels 1.19.2-1.2
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		leave_slab: Leaves mod 0.0.1-1.19
		legendarytooltips: Legendary Tooltips 1.3.3
		libraryferret: Library ferret 3.0.0
		lightwithin: LightWithin Mod 0.3.0
			renderer: Renderer 1.0
			structureplacerapi: StructurePlacerAPI 1.0.1
		mcda: MC Dungeons Armors 2.2.0
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
		medievalweapons: Medieval Weapons 1.4.1
		midnightlib: MidnightLib 0.6.1
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mobvote2022: Mob Vote 2022 1.0
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.0.37
		moyai: moyai 1.19.2-2.0.0
		musketmod: Musket Mod 1.4.5
		mysticalcrops: Mystical Nature 1.5-1.19.2
		mythicmetals: Mythic Metals 0.16.2+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.0
		notenoughanimations: NotEnoughAnimations 1.6.1
		origins: Origins 1.7.0
			apoli: Apoli 2.6.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		originsumbrellas: Origins: Umbrellas 1.5.4
		owo: oωo 0.8.4+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-76-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.5.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		philips_ruins__fabric: Philips ruins 1.19.2 fabric 1.8
		philipsruins: Philip`s ruins 1.19.2
		player-animator: Player Animator 0.3.5
		playerex: PlayerEx 3.3.7
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		presencefootsteps: Presence Footsteps 1.6.2
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.1
		radiantgear: Radiant Gear 2.0.0+1.19.2
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 0.1.0
		roughlyenoughitems: Roughly Enough Items 9.1.554
			error_notifier: Error Notifier 1.0.9
		rpgz: RPGZ 0.5.3
		scout: Scout 1.1.1
		simplyswords: Simply Swords 1.31-1.19.x
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		sky: Sky: Origins 0.6.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulsweapons: Marium's Soulslike Weaponry 0.9.5
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b2
		strongersnowballs: StrongerSnowballs 9.0.1
		structory: Structory 1.0.1
		subterrestrial: Subterrestrial 1.0.3
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		techno_blade: Techno-Blade 1.0.0
		terrablender: TerraBlender 2.0.1.127
		the_bumblezone: The Bumblezone - Fabric 6.1.14+1.19.2
			fake-player-api: Fake Player API 0.4.0
		toolstats: ToolStats 12.0.2
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		totw_additions: Towers of the Wild: Additions 1.2.3
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.2
		utilitybelt: Utility Belt 1.1.1
		vanilla_claws: Vanilla Claws 1.0.1
		vanityslots: Vanity Slots 1.2.1
		victus: Victus 0.1.12+1.19
		wabi_sabi_structures: Wabi-Sabi Structures 1.0.3
		warhammersmod: War-Hammers Mod 1.0.4
		weaponmaster: YDM's Weapon Master 3.0.2
		whipdashing: Whipdashing 1.0.2+1.19.x
		wildlife: Wildlife 1.19.2-2.1
		winterly: Winterly 0.7.2
		wondrouswilds: Wondrous Wilds 1.19-1.1.2
		woodarmor: Wooden Armors (+ Stone Armor) 1.0.2
		woof: Woof 2.0.2-1.19
		yet-another-config-lib: YetAnotherConfigLib 1.5.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.0
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0

Additionally I have tested both with shaders on and off in case that possibly was causing the issue, however with no difference.

**Comment by Emafire003** [comment]
Sorry, I didn't have time to update to the new version of ColoredGlowLib, so keep using version 1.4.0,  I will release a new version of LightWithin soon-ish

**Comment by Tr33stan** [comment]
Ah okay! That makes sense :) No worries as well! Thanks for the swift reply, keeping up with someone else's updates is always difficult haha. There's a version of LightWithin above 0.3.0? It doesn't appear to be on Curseforge or Modrinth.

**Comment by Emafire003** [comment]
Well that someone else is still me, but xD. Oh and for the lightwithin version my mistake, I got confused between the one I was working on the one I released eh eh.

**Comment by Tr33stan** [comment]
Got it working as intended by using just the bundled version of the mod, which I should've seen and used in the first place lol.
Just wanted to also say that having had to now get my hands on and test the mod, it's held up really well even in what I expected to be problematic circumstances (Victus hearts, Origin health changes, etc) and both the concept itself and the visuals are really immersive and fascinating! One question though, does the Luxmuta berry change the target type? Trying to bugtest and it seems while I can get any and all of the POWER types, it doesn't seem to change to SELF target ever since I started with seemingly another condition according to my UUID. Is there a way to manually set light types and target conditions?

**Comment by Emafire003** [comment]
Nope, it doesn't yet. I have it in my TODO list, but it got a bit down the list since I also have to decide weather to add that feature to the same berry or make a new one. But, a while back I introuduced a series of commands, beginning with /light that allow you to change pretty much anything of your/someone else's light. iirc for changing the target type should be /light set target <targettype>. Not all lights support all target types, in fact if you change your light type, and you get a light that doesn't support your target type that will change as well. I'm not sure what you mean by "target conditions" tho, hope this helped anyway. And yes, I am going to make proper wiki with the next release, but I had (and still have) a lot of stuff that needs my attention now. So it could be a week or two before the next update. 

Also, thanks for the complimentes!
